### ISSUE TITLE
Opting out of transactions for some migrations

### ISSUE THREAD

**Issue by pd** [rnubel/pgmgr#9]
I'd like to implement something that provides a feature similar to [ActiveRecord::Migration#disable_ddl_transaction!](http://api.rubyonrails.org/classes/ActiveRecord/Migration.html#method-c-disable_ddl_transaction-21). Mostly so I can run `CREATE INDEX CONCURRENTLY ...`.

I've currently got two ideas for how this could happen:

1. Magic comments, eg `-- transaction: false` or such.
2. Encode it in the filenames, eg `<ts>_<name>.notx.up.sql` or such.

Option 1 reminds me of tools I didn't like using, and means we'd have to read the migration and do some juggling of the contents before we could run them.

Option 2 is simpler, but if another option comes along, suddenly we gotta figure out how to encode that into the filename as well. I can't think of any other useful options, tho.

You into either of these? Or got any other ideas?

**Comment by rnubel** [comment]
I'm leaning towards Option 2, since we already encode metadata in the filenames (direction), with the future direction being that we just add more "tags" as needed, like `20150911010101_do_stuff.master_first.no_txn.up.sql`. The migration code in pgmgr will have to use a regex or something to extract all the tags before running anything, but that seems doable. 

Either way, running `pgmgr migration --no-txn DoStuff` should create an appropriately-formatted migration.
